# Generated by Django 2.2.5 on 2020-01-10 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20200110_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_iden', models.CharField(max_length=15, verbose_name='采购订单编号')),
                ('po_serial', models.CharField(max_length=4, verbose_name='采购订单流水号')),
                ('po_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='采购订单生效日期')),
                ('po_sum', models.IntegerField(verbose_name='采购订单总额')),
                ('po_remarks', models.TextField(max_length=400, verbose_name='采购订单备注')),
                ('pc_iden', models.CharField(max_length=15, null=True, verbose_name='采购合同编号')),
                ('po_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='采购订单状态')),
                ('po_creator', models.CharField(max_length=20, verbose_name='采购订单创建者名字')),
                ('po_creator_iden', models.CharField(max_length=20, verbose_name='采购订单创建者编号')),
                ('po_createDate', models.DateTimeField(auto_now_add=True, verbose_name='采购订单创建时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_po', to='base.Organization', verbose_name='组织')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_po', to='base.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购订单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_iden', models.CharField(max_length=15, verbose_name='合同编号')),
                ('pc_serial', models.CharField(max_length=4, verbose_name='合同流水号')),
                ('pc_name', models.CharField(max_length=20, verbose_name='合同名称')),
                ('pc_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='合同签订日期')),
                ('pc_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='合同总额')),
                ('pc_remarks', models.TextField(max_length=400, null=True, verbose_name='合同备注')),
                ('pc_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='合同状态')),
                ('pc_creator', models.CharField(max_length=20, verbose_name='合同创建者名字')),
                ('pc_creator_iden', models.CharField(max_length=20, verbose_name='合同创建者工号')),
                ('pc_createDate', models.DateTimeField(auto_now_add=True, verbose_name='合同创建时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_pc', to='base.Organization', verbose_name='组织')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_pc', to='base.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购合同',
            },
        ),
        migrations.CreateModel(
            name='OrDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('od_num', models.IntegerField(verbose_name='采购数量')),
                ('od_taxRate', models.IntegerField(default=13, verbose_name='税率')),
                ('od_tax_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='含税单价')),
                ('od_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税单价')),
                ('od_tax_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='含税总额')),
                ('od_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税总额')),
                ('od_pr_iden', models.CharField(max_length=15, verbose_name='请购单编号')),
                ('od_prd_remarks', models.TextField(max_length=400, verbose_name='物料备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_od', to='base.Material', verbose_name='物料')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_od', to='purchase.PurchaseOrder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购订单详情',
            },
        ),
        migrations.CreateModel(
            name='CdPayDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_batch', models.IntegerField(verbose_name='付款批次')),
                ('pay_rate', models.IntegerField(verbose_name='付款比率')),
                ('pay_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='付款金额')),
                ('pay_planDate', models.DateField(verbose_name='计划付款日期')),
                ('pay_prepay', models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否预付款')),
                ('pay_remarks', models.TextField(max_length=400, null=True, verbose_name='付款备注')),
                ('purchase_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_pay', to='purchase.PurchaseContract', verbose_name='采购合同')),
            ],
            options={
                'verbose_name': '合同付款协议',
            },
        ),
        migrations.CreateModel(
            name='CdDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_num', models.IntegerField(verbose_name='物料数量')),
                ('cd_taxRate', models.IntegerField(default=13, null=True, verbose_name='税率')),
                ('cd_tax_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='含税单价')),
                ('cd_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='无税单价')),
                ('cd_tax_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='含税总额')),
                ('cd_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='无税总额')),
                ('cd_unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='税额')),
                ('cd_pr_iden', models.CharField(max_length=15, verbose_name='请购单编号')),
                ('cd_prd_remarks', models.TextField(max_length=400, null=True, verbose_name='物料备注')),
                ('cd_used', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='明细单是否使用')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_cd', to='base.Material', verbose_name='物料')),
                ('purchase_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_cd', to='purchase.PurchaseContract', verbose_name='采购合同')),
            ],
            options={
                'verbose_name': '合同物料明细',
            },
        ),
    ]
