# Generated by Django 2.2.5 on 2020-01-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cddetail',
            old_name='cd_unit_price',
            new_name='cd_tax_price',
        ),
    ]
