# Generated by Django 2.2.5 on 2020-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdetail',
            name='prd_remarks',
            field=models.TextField(max_length=400, null=True, verbose_name='物料请购备注'),
        ),
    ]
