# Generated by Django 2.2.5 on 2020-01-10 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellorder',
            name='deliver_ware_house_iden',
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='so_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='订单日期'),
        ),
    ]
