# Generated by Django 2.2.5 on 2019-12-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_present_num', models.IntegerField(verbose_name='物料现存量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ts', to='base.Material', verbose_name='物料')),
                ('totalwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_ware_house_ts', to='base.TotalWareHouse', verbose_name='总仓')),
            ],
        ),
        migrations.CreateModel(
            name='CenterStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_present_num', models.IntegerField(verbose_name='物料现存量')),
                ('centerwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_ware_house_cs', to='base.CenterWareHouse', verbose_name='中心仓库')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_cs', to='base.Material', verbose_name='物料')),
            ],
        ),
    ]
