# Generated by Django 2.2.5 on 2020-01-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstock',
            name='totalwarehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_ware_house_ts', to='base.TotalWareHouse', verbose_name='仓库'),
        ),
        migrations.DeleteModel(
            name='CenterStock',
        ),
    ]
