# Generated by Django 2.2.5 on 2020-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeManage', '0002_auto_20200103_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstock',
            name='ts_present_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='库存单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalstock',
            name='ts_present_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='库存总额'),
            preserve_default=False,
        ),
    ]
