# Generated by Django 2.2.5 on 2019-12-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_name', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '区域',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='品牌名称')),
                ('brand_description', models.TextField(max_length=400, verbose_name='品牌描述')),
                ('brand_creator', models.CharField(max_length=20, verbose_name='品牌创建者')),
                ('brand_createDate', models.DateTimeField(auto_now_add=True, verbose_name='品牌创建时间')),
            ],
            options={
                'verbose_name': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_iden', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='客户编码')),
                ('customer_name', models.CharField(max_length=20, verbose_name='客户名称')),
                ('customer_type', models.IntegerField(choices=[(0, '内部单位'), (1, '外部单位')], default=0, verbose_name='客户类型')),
                ('customer_remarks', models.TextField(max_length=400, verbose_name='客户备注')),
                ('customer_creator', models.CharField(max_length=20, verbose_name='客户创建者')),
                ('customer_createDate', models.DateTimeField(auto_now_add=True, verbose_name='客户创建时间')),
            ],
            options={
                'verbose_name': '客户',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpm_name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('dpm_remarks', models.TextField(max_length=400, verbose_name='部门备注')),
                ('dpm_center', models.IntegerField(choices=[(0, '非中心部门'), (1, '中心')], default=0, verbose_name='是否中心')),
                ('dpm_creator', models.CharField(max_length=20, verbose_name='部门创建人')),
                ('dpm_createDate', models.DateTimeField(auto_now_add=True, verbose_name='部门创建时间')),
            ],
            options={
                'verbose_name': '部门',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('type_iden', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='物料类别编码')),
                ('type_name', models.CharField(max_length=20, verbose_name='物料类别名称')),
                ('type_creator', models.CharField(max_length=20, verbose_name='物料类别创建者')),
                ('type_createDate', models.DateTimeField(auto_now_add=True, verbose_name='物料创建时间')),
            ],
            options={
                'verbose_name': '计量单位',
            },
        ),
        migrations.CreateModel(
            name='Meterage',
            fields=[
                ('meterage_iden', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='计量单位编码')),
                ('meterage_name', models.CharField(max_length=20, verbose_name='计量单位名称')),
                ('meterage_dimension', models.IntegerField(choices=[(0, '重量'), (1, '长度'), (2, '面积'), (3, '体积'), (4, '件数')], verbose_name='计量单位量纲')),
                ('meterage_creator', models.CharField(max_length=20, verbose_name='计量单位创建者')),
                ('meterage_createDate', models.DateTimeField(auto_now_add=True, verbose_name='计量单位创建时间')),
            ],
            options={
                'verbose_name': '计量单位',
            },
        ),
        migrations.CreateModel(
            name='Origanization',
            fields=[
                ('orga_iden', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='组织编码')),
                ('orga_name', models.CharField(max_length=20, verbose_name='组织名称')),
                ('orga_remarks', models.TextField(max_length=400, verbose_name='组织备注')),
                ('orga_creator', models.CharField(max_length=20, verbose_name='组织创建者')),
                ('orga_createDate', models.DateTimeField(auto_now_add=True, verbose_name='组织创建时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_orga', to='base.Area', verbose_name='区域')),
            ],
            options={
                'verbose_name': '组织',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='角色名称')),
                ('role_description', models.TextField(max_length=400, verbose_name='角色描述')),
                ('role_creator', models.CharField(max_length=20, verbose_name='角色创建人')),
                ('role_createData', models.DateTimeField(auto_now_add=True, verbose_name='创建角色时间')),
            ],
            options={
                'verbose_name': '角色',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supply_iden', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='供应商编码')),
                ('supply_name', models.CharField(max_length=20, verbose_name='供应商名称')),
                ('supply_type', models.IntegerField(choices=[(0, '内部单位'), (1, '外部单位')], default=0, verbose_name='供应商类型')),
                ('supply_remarks', models.TextField(max_length=400, verbose_name='供应商备注')),
                ('supply_creator', models.CharField(max_length=20, verbose_name='供应商创建者')),
                ('supply_createDate', models.DateTimeField(auto_now_add=True, verbose_name='供应商创建时间')),
            ],
            options={
                'verbose_name': '供应商',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='工号')),
                ('user_passwd', models.CharField(default=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='工号'), max_length=20, verbose_name='用户密码')),
                ('user_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('user_phone_number', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('user_mailbox', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('user_departments', models.CharField(max_length=50, verbose_name='部门')),
                ('user_roles', models.CharField(max_length=50, verbose_name='角色')),
                ('user_status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], verbose_name='员工状态')),
                ('user_creator', models.CharField(max_length=20, verbose_name='员工创建人')),
                ('user_createDate', models.DateTimeField(auto_now_add=True, verbose_name='员工创建时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_user', to='base.Area', verbose_name='区域')),
            ],
            options={
                'verbose_name': '员工',
            },
        ),
        migrations.CreateModel(
            name='TotalWareHouse',
            fields=[
                ('total_iden', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='总仓库编码')),
                ('total_name', models.CharField(max_length=20, verbose_name='总仓名字')),
                ('total_remarks', models.TextField(max_length=400, verbose_name='总仓备注')),
                ('total_creator', models.CharField(max_length=20, verbose_name='总仓创建者')),
                ('total_createDate', models.DateTimeField(auto_now_add=True, verbose_name='总仓创建时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Brand', verbose_name='品牌')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_total_ware_house', to='base.Origanization')),
            ],
            options={
                'verbose_name': '总仓',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_iden', models.CharField(max_length=35, primary_key=True, serialize=False, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=20, verbose_name='物料名称')),
                ('material_specification', models.CharField(max_length=30, verbose_name='物料规格')),
                ('material_model', models.CharField(max_length=30, verbose_name='物料型号')),
                ('material_attr', models.IntegerField(choices=[(0, '存货'), (1, '固定资产'), (2, '费用')], verbose_name='存货属性')),
                ('material_creator', models.CharField(max_length=20, verbose_name='物料创建者')),
                ('material_createDate', models.DateTimeField(auto_now_add=True, verbose_name='物料创建时间')),
                ('meterage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meterage_material', to='base.Meterage', verbose_name='计量单位')),
            ],
            options={
                'verbose_name': '物料',
            },
        ),
        migrations.CreateModel(
            name='CenterWareHouse',
            fields=[
                ('center_wh_iden', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='中心仓库编码')),
                ('center_wh_name', models.CharField(max_length=20, verbose_name='中心仓库名字')),
                ('center_wh_remarks', models.TextField(max_length=400, verbose_name='中心仓库备注')),
                ('center_wh_creator', models.CharField(max_length=20, verbose_name='中心创建者')),
                ('center_wh_createDate', models.DateTimeField(auto_now_add=True, verbose_name='中心创建时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Brand', verbose_name='品牌')),
                ('origanization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_center_ware_house', to='base.Origanization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '中心仓库',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=20, verbose_name='中心名称')),
                ('center_remarks', models.TextField(max_length=400, verbose_name='中心备注')),
                ('center_creator', models.CharField(max_length=20, verbose_name='中心创建者')),
                ('center_createDate', models.DateTimeField(auto_now_add=True, verbose_name='中心创建时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_center', to='base.Area', verbose_name='区域')),
            ],
            options={
                'verbose_name': '中心',
            },
        ),
    ]
