# Generated by Django 2.2.5 on 2019-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_mailbox',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_phone_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
