# Generated by Django 2.2.5 on 2019-12-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191231_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='area',
            new_name='area_name',
        ),
    ]
