# Generated by Django 2.2.5 on 2019-12-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20191231_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='role_name',
        ),
    ]
