# Generated by Django 2.2.5 on 2020-01-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20191231_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='area',
            new_name='area_name',
        ),
        migrations.RenameField(
            model_name='origanization',
            old_name='area',
            new_name='area_name',
        ),
    ]
