# Generated by Django 2.2.5 on 2020-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200101_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_power',
            field=models.CharField(max_length=60, null=True, verbose_name='角色权限'),
        ),
    ]
