# Generated by Django 2.2.5 on 2020-01-01 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_role_role_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerwarehouse',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_center_wh', to='base.Center', verbose_name='所属中心'),
            preserve_default=False,
        ),
    ]
