# Generated by Django 2.2.5 on 2020-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200101_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='meterage_type_iden',
            field=models.CharField(default=1, max_length=30, verbose_name='分类编码'),
            preserve_default=False,
        ),
    ]
