# Generated by Django 2.2.5 on 2020-01-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_material_meterage_type_iden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': '物料类别'},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='meterage_type_iden',
            new_name='material_type_iden',
        ),
    ]
