# Generated by Django 2.2.5 on 2020-01-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200102_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='role',
        ),
    ]
