# Generated by Django 2.2.5 on 2020-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeManage', '0002_auto_20200103_1453'),
        ('base', '0014_auto_20200102_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalwarehouse',
            name='total_belong_center',
            field=models.CharField(max_length=20, null=True, verbose_name='所属中心编号'),
        ),
        migrations.DeleteModel(
            name='CenterWareHouse',
        ),
    ]
