# Generated by Django 2.2.5 on 2020-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200103_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_iden', models.CharField(max_length=20, verbose_name='登录工号')),
                ('user_name', models.CharField(max_length=20, verbose_name='登录人名字')),
                ('area_name', models.CharField(max_length=20, verbose_name='登录人区域')),
                ('user_departments', models.CharField(max_length=20, verbose_name='登录人部门')),
                ('user_roles', models.CharField(max_length=20, verbose_name='登录人角色')),
            ],
            options={
                'verbose_name': '当前登录',
            },
        ),
    ]
