# Generated by Django 2.2.5 on 2020-01-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_usernow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_createData',
            new_name='role_createDate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_creator_name',
            field=models.CharField(default=1, max_length=20, verbose_name='员工创建人名字'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_creator',
            field=models.CharField(max_length=20, verbose_name='员工创建人工号'),
        ),
    ]
