# Generated by Django 2.2.5 on 2020-01-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200104_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_creator_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='品牌创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='center_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='中心创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='客户创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='dpm_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='部门创建人工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='material_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='物料创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialtype',
            name='type_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='物料类别创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meterage',
            name='meterage_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='计量单位创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='orga_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='组织创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='role_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='角色创建人工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='供应商创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalwarehouse',
            name='total_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='总仓创建者工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_creator_iden',
            field=models.CharField(default=1, max_length=20, verbose_name='员工创建人工号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_creator',
            field=models.CharField(max_length=20, verbose_name='品牌创建者名字'),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_creator',
            field=models.CharField(max_length=20, verbose_name='中心创建者名字'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_creator',
            field=models.CharField(max_length=20, verbose_name='客户创建者名字'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dpm_creator',
            field=models.CharField(max_length=20, verbose_name='部门创建人名字'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_creator',
            field=models.CharField(max_length=20, verbose_name='物料创建者名字'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='type_creator',
            field=models.CharField(max_length=20, verbose_name='物料类别创建者名字'),
        ),
        migrations.AlterField(
            model_name='meterage',
            name='meterage_creator',
            field=models.CharField(max_length=20, verbose_name='计量单位创建者名字'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orga_creator',
            field=models.CharField(max_length=20, verbose_name='组织创建者名字'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_creator',
            field=models.CharField(max_length=20, verbose_name='角色创建人名字'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supply_creator',
            field=models.CharField(max_length=20, verbose_name='供应商创建者名字'),
        ),
        migrations.AlterField(
            model_name='totalwarehouse',
            name='total_creator',
            field=models.CharField(max_length=20, verbose_name='总仓创建者名字'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_creator',
            field=models.CharField(max_length=20, verbose_name='员工创建人名字'),
        ),
    ]
