# Generated by Django 2.2.5 on 2020-01-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200104_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernow',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='人员id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalwarehouse',
            name='brand_name',
            field=models.CharField(max_length=20, null=True, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
