# Generated by Django 2.2.5 on 2020-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20200104_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalwarehouse',
            name='total_belong_iden',
            field=models.CharField(max_length=20, null=True, verbose_name='所属中心的编号'),
        ),
        migrations.AlterField(
            model_name='totalwarehouse',
            name='total_belong_center',
            field=models.CharField(max_length=20, null=True, verbose_name='所属中心的名字'),
        ),
    ]
