# Generated by Django 2.2.5 on 2020-01-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200104_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_iden',
        ),
    ]
