# Generated by Django 2.2.5 on 2020-01-10 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20200110_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('str_iden', models.CharField(max_length=15, verbose_name='转库申请单编号')),
                ('str_serial', models.CharField(max_length=4, verbose_name='转库申请单流水号')),
                ('str_to_house', models.CharField(max_length=20, verbose_name='转入仓库名字')),
                ('str_from_house', models.CharField(max_length=20, verbose_name='转出仓库名字')),
                ('str_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='转库申请日期')),
                ('str_department', models.CharField(max_length=20, verbose_name='转库申请部门')),
                ('str_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], verbose_name='转库申请单状态')),
                ('str_creator', models.CharField(max_length=20, verbose_name='转库出库单创建人名字')),
                ('str_creator_iden', models.CharField(max_length=20, verbose_name='转库出库单创建人工号')),
                ('str_createDate', models.DateTimeField(auto_now_add=True, verbose_name='销售出库单创建日期')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_str', to='base.Organization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '转库申请单',
            },
        ),
        migrations.CreateModel(
            name='TrDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trd_num', models.IntegerField(verbose_name='转库申请数量')),
                ('trd_present_num', models.IntegerField(verbose_name='材料现存量')),
                ('trd_used', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='是否使用过')),
                ('trd_remarks', models.TextField(max_length=400, verbose_name='转库单明细备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_trd', to='base.Material', verbose_name='物料')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_trd', to='storeAdjust.TransferRequest', verbose_name='转库申请单')),
            ],
            options={
                'verbose_name': '转库申请单详情',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('st_iden', models.CharField(max_length=15, verbose_name='转库单编号')),
                ('st_serial', models.CharField(max_length=4, verbose_name='转库单流水号')),
                ('st_to_house', models.CharField(max_length=20, verbose_name='转入仓库名字')),
                ('st_from_house', models.CharField(max_length=20, verbose_name='转出仓库名字')),
                ('st_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='转库日期')),
                ('st_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], verbose_name='转库单状态')),
                ('st_creator', models.CharField(max_length=20, verbose_name='转库单创建者名字')),
                ('st_creator_iden', models.CharField(max_length=20, verbose_name='转库单创建者编号')),
                ('st_createDate', models.DateTimeField(auto_now_add=True, verbose_name='转库单创建时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orga_st', to='base.Organization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '转库单',
            },
        ),
        migrations.CreateModel(
            name='StDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('str_iden', models.CharField(max_length=15, null=True, verbose_name='转库申请单编号')),
                ('td_apply_num', models.IntegerField(verbose_name='转库申请数量')),
                ('td_real_num', models.IntegerField(verbose_name='转库实发数量')),
                ('td_present_num', models.IntegerField(verbose_name='材料现存量')),
                ('td_remarks', models.TextField(max_length=400, verbose_name='转库单明细备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_td', to='base.Material', verbose_name='物料')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_td', to='storeAdjust.Transfer', verbose_name='转库单')),
            ],
            options={
                'verbose_name': '转库单明细',
            },
        ),
    ]
